service: sssr-nuxt

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${self:custom.secrets.NODE_ENV, 'prod'}
  region: ${opt:region, 'us-east-1'}
  httpApi:
    disableDefaultEndpoint: true
    cors: true
  apiGateway:
    shouldStartNameWithService: true
  timeout: 5
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

functions:
  nuxt:
    handler: .output/server/index.handler
    events:
      - httpApi: '*'

custom:
  secrets: ${file(secrets.json)}
